// This file is auto-generated by the Vite plugin in vite.config.ts.
// It lists all images under /public/gallery so the app can render them automatically.
// Supported formats: jpg, jpeg, png, webp, avif, gif, svg
// Do not edit manually; your changes will be overwritten on next dev start/build.

export const galleryPublicManifest: { src: string; alt: string }[] = [
  {
    "src": "/gallery/10.jpg",
    "alt": "10"
  },
  {
    "src": "/gallery/11.png",
    "alt": "11"
  },
  {
    "src": "/gallery/2.jpg",
    "alt": "2"
  },
  {
    "src": "/gallery/3.jpg",
    "alt": "3"
  },
  {
    "src": "/gallery/4.jpg",
    "alt": "4"
  },
  {
    "src": "/gallery/5.jpg",
    "alt": "5"
  },
  {
    "src": "/gallery/6.jpg",
    "alt": "6"
  },
  {
    "src": "/gallery/7.jpg",
    "alt": "7"
  },
  {
    "src": "/gallery/8.jpg",
    "alt": "8"
  },
  {
    "src": "/gallery/9.jpg",
    "alt": "9"
  }
]
;
